apiVersion: v1
kind: Service
metadata:
  name: portfolio-accounting-service
  namespace: globeco
  labels:
    app.kubernetes.io/name: globeco-portfolio-accounting
    app.kubernetes.io/instance: production
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: api-server
    app.kubernetes.io/part-of: globeco-suite
    app.kubernetes.io/managed-by: kubernetes
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    prometheus.io/scrape: "true"
    prometheus.io/port: "8087"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
  - port: 8087
    targetPort: 8087
    protocol: TCP
    name: http-api
  selector:
    app.kubernetes.io/name: globeco-portfolio-accounting
    app.kubernetes.io/component: api-server
  sessionAffinity: None

---
apiVersion: v1
kind: Service
metadata:
  name: portfolio-accounting-headless
  namespace: globeco
  labels:
    app.kubernetes.io/name: globeco-portfolio-accounting
    app.kubernetes.io/instance: production
    app.kubernetes.io/component: api-server-headless
spec:
  type: ClusterIP
  clusterIP: None  # Headless service for direct pod communication
  ports:
  - port: 8087
    targetPort: 8087
    protocol: TCP
    name: http-api
  selector:
    app.kubernetes.io/name: globeco-portfolio-accounting
    app.kubernetes.io/component: api-server

---
apiVersion: v1
kind: Service
metadata:
  name: portfolio-accounting-metrics
  namespace: globeco
  labels:
    app.kubernetes.io/name: globeco-portfolio-accounting
    app.kubernetes.io/instance: production
    app.kubernetes.io/component: metrics
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8087"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
  - port: 8087
    targetPort: 8087
    protocol: TCP
    name: metrics
  selector:
    app.kubernetes.io/name: globeco-portfolio-accounting
    app.kubernetes.io/component: api-server

---
apiVersion: v1
kind: Service
metadata:
  name: portfolio-accounting-nodeport
  namespace: globeco
  labels:
    app.kubernetes.io/name: globeco-portfolio-accounting
    app.kubernetes.io/instance: production
    app.kubernetes.io/component: api-server-external
  annotations:
    description: "NodePort service for external access during development"
spec:
  type: NodePort
  ports:
  - port: 8087
    targetPort: 8087
    nodePort: 30087
    protocol: TCP
    name: http-api
  selector:
    app.kubernetes.io/name: globeco-portfolio-accounting
    app.kubernetes.io/component: api-server

---
# Service for CLI operations (if needed)
apiVersion: v1
kind: Service
metadata:
  name: portfolio-accounting-cli
  namespace: globeco
  labels:
    app.kubernetes.io/name: globeco-portfolio-accounting
    app.kubernetes.io/instance: production
    app.kubernetes.io/component: cli
spec:
  type: ClusterIP
  clusterIP: None  # Headless service for CLI pods
  ports:
  - port: 22
    targetPort: 22
    protocol: TCP
    name: ssh
  selector:
    app.kubernetes.io/name: globeco-portfolio-accounting
    app.kubernetes.io/component: cli

---
# Service Monitor for Prometheus Operator
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: portfolio-accounting-monitor
  namespace: globeco
  labels:
    app.kubernetes.io/name: globeco-portfolio-accounting
    app.kubernetes.io/instance: production
    app.kubernetes.io/component: monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: globeco-portfolio-accounting
      app.kubernetes.io/component: api-server
  endpoints:
  - port: http-api
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
    scheme: http
  namespaceSelector:
    matchNames:
    - globeco-portfolio-accounting

---
# Service for database migrations (Job-based)
apiVersion: v1
kind: Service
metadata:
  name: portfolio-accounting-migration
  namespace: globeco
  labels:
    app.kubernetes.io/name: globeco-portfolio-accounting
    app.kubernetes.io/instance: production
    app.kubernetes.io/component: migration
spec:
  type: ClusterIP
  clusterIP: None  # Headless service for migration jobs
  ports:
  - port: 80
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: globeco-portfolio-accounting
    app.kubernetes.io/component: migration 