# GlobeCo Portfolio Accounting Service Configuration
# Copy this file to config.yaml and modify as needed

server:
  host: "0.0.0.0"
  port: 8087
  read_timeout: "30s"
  write_timeout: "30s"
  idle_timeout: "120s"
  graceful_shutdown_timeout: "30s"

database:
  host: "globeco-portfolio-accounting-service-postgresql"
  port: 5432
  user: "postgres"
  password: ""
  database: "postgres"
  ssl_mode: "disable"
  max_open_conns: 25
  max_idle_conns: 5
  conn_max_lifetime: "15m"
  migrations_path: "migrations"
  auto_migrate: true       # Automatically run migrations on startup

cache:
  enabled: true
  hosts:
    - "globeco-portfolio-accounting-service-cache:5701"
  cluster_name: "globeco-portfolio-accounting"
  username: ""
  password: ""
  ttl: "1h"
  timeout: "5s"

kafka:
  enabled: false
  brokers:
    - "portfolio-execution-service-kafka:9092"
  topic: "portfolio-accounting-events"
  group_id: "portfolio-accounting-service"
  batch_size: 100
  timeout: "10s"

logging:
  level: "info"        # debug, info, warn, error
  format: "json"       # json, console
  output: "stdout"     # stdout, stderr, or file path
  structured: true

metrics:
  enabled: true
  path: "/metrics"
  port: 9090

tracing:
  enabled: true
  service_name: "globeco-portfolio-accounting-service"
  endpoint: "http://localhost:14268/api/traces"
  sample_rate: 0.1

external:
  portfolio_service:
    host: "globeco-portfolio-service"
    port: 8001
    timeout: "30s"
    max_retries: 3
    retry_backoff: "1s"
    circuit_breaker_threshold: 5
  
  security_service:
    host: "globeco-security-service"
    port: 8000
    timeout: "30s"
    max_retries: 3
    retry_backoff: "1s"
    circuit_breaker_threshold: 5 