apiVersion: v1
kind: ConfigMap
metadata:
  name: portfolio-accounting-config
  namespace: globeco
  labels:
    app.kubernetes.io/name: globeco-portfolio-accounting
    app.kubernetes.io/instance: production
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: config
    app.kubernetes.io/part-of: globeco-suite
    app.kubernetes.io/managed-by: kubernetes
data:
  config.yaml: |
    server:
      host: "0.0.0.0"
      port: 8087
      read_timeout: 30s
      write_timeout: 30s
      idle_timeout: 60s
      shutdown_timeout: 30s
      cors:
        allowed_origins:
          - "*"
        allowed_methods:
          - "GET"
          - "POST"
          - "PUT"
          - "DELETE"
          - "OPTIONS"
        allowed_headers:
          - "*"
        max_age: 3600

    database:
      driver: "postgres"
      host: "postgresql-service.globeco-portfolio-accounting.svc.cluster.local"
      port: 5432
      name: "portfolio_accounting"
      username: "portfolio_user"
      max_open_conns: 25
      max_idle_conns: 10
      conn_max_lifetime: 300s
      migration_path: "./migrations"

    cache:
      type: "hazelcast"
      hosts:
        - "hazelcast-service.globeco-portfolio-accounting.svc.cluster.local:5701"
      cluster_name: "portfolio-accounting-cluster"
      ttl: 3600s

    kafka:
      brokers:
        - "kafka-service.globeco-portfolio-accounting.svc.cluster.local:9092"
      topic: "portfolio-transactions"
      group_id: "portfolio-accounting-service"
      auto_offset_reset: "earliest"
      enable_auto_commit: true
      session_timeout: 30s

    external_services:
      portfolio_service:
        base_url: "http://globeco-portfolio-service.globeco-portfolio.svc.cluster.local:8001"
        timeout: 30s
        retry_attempts: 3
        circuit_breaker:
          max_requests: 100
          interval: 60s
          timeout: 60s
      security_service:
        base_url: "http://globeco-security-service.globeco-security.svc.cluster.local:8000"
        timeout: 30s
        retry_attempts: 3
        circuit_breaker:
          max_requests: 100
          interval: 60s
          timeout: 60s

    logging:
      level: "info"
      format: "json"
      output: "stdout"
      enable_caller: true
      enable_stacktrace: false

    metrics:
      enabled: true
      path: "/metrics"
      namespace: "portfolio_accounting"

    health:
      path: "/health"
      port: 8087

    tracing:
      enabled: true
      service_name: "portfolio-accounting-service"
      jaeger_endpoint: "http://jaeger-collector.observability.svc.cluster.local:14268/api/traces"
      sampling_rate: 0.1

  # Application environment variables
  APP_ENV: "production"
  LOG_LEVEL: "info"
  METRICS_ENABLED: "true"
  TRACING_ENABLED: "true"
  
  # Cache configuration
  CACHE_TTL: "3600"
  CACHE_CLUSTER_NAME: "portfolio-accounting-cluster"
  
  # Database configuration
  DB_MAX_OPEN_CONNS: "25"
  DB_MAX_IDLE_CONNS: "10"
  DB_CONN_MAX_LIFETIME: "300s"
  DB_AUTO_MIGRATE: "true"
  
  # HTTP server configuration
  SERVER_READ_TIMEOUT: "30s"
  SERVER_WRITE_TIMEOUT: "30s"
  SERVER_IDLE_TIMEOUT: "60s"
  
  # External service timeouts
  PORTFOLIO_SERVICE_TIMEOUT: "30s"
  SECURITY_SERVICE_TIMEOUT: "30s"
  
  # Kafka configuration
  KAFKA_GROUP_ID: "portfolio-accounting-service"
  KAFKA_AUTO_OFFSET_RESET: "earliest"
  
  # JVM Options for Hazelcast (if needed)
  JAVA_OPTS: "-Xms512m -Xmx1024m -XX:+UseG1GC -XX:MaxGCPauseMillis=200"

