apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: portfolio-accounting-service-postgres-pvc
  namespace: globeco
  labels:
    app: portfolio-accounting-service-postgres
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-gp3
  resources:
    requests:
      storage: 10Gi
